---
# tasks file for dkron_cluster
- name: create dkron config file for clustering
  ansible.builtin.copy:
    content: |
      server: true
      bind-addr: "{{ inventory_hostname }}:{{ dkron_bind_port }}"
      http-addr: "{{ dkron_http_addr }}"
      bootstrap-expect: {{ dkron_hosts | length }}
      join: 
        {{ dkron_hosts | sort | difference([hostvars[inventory_hostname]['ansible_default_ipv4']['address']]) | to_nice_yaml | trim | indent(2) }}
    dest: /etc/dkron/dkron.yml
  notify:
  - restart dkron
